### ISSUE TITLE
Support RevealJS chalkboard

### ISSUE THREAD

**Issue by neilernst** [grantmcdermott/quarto-revealjs-clean#1]
I'm trying to use this with the Reveal [Chalkboard](https://quarto.org/docs/presentations/revealjs/presenting.html#chalkboard) plugin, but it doesn't work. Perhaps it is my config. My header looks something like:

```
---
title: My Title
format:
  clean-revealjs: default
  revealjs: 
    chalkboard: true
author:
  - name: Neil Ernst
date: last-modified
---
```

I'm guessing there is some issue in the `format:` key with order? I tried both clean first and last.

**Comment by coatless** [comment]
@neilernst place the options you want passed to `revealjs` under the desired format, e.g.:

```markdown
---
title: My Title
format:
  clean-revealjs:
    chalkboard: true
author:
  - name: Neil Ernst
date: last-modified
---
```

Then, pressing `c` opens the chalkboard.

**Comment by neilernst** [comment]
Thanks! where does the `clean-revealjs: default` go? I would guess as default it doesn't need to be stated explicitly.

**Comment by coatless** [comment]
The `default` component just indicates that no other `revealjs` options will be passed in. Since we're specifying `chalkboard: true`, we can no longer use the `default` entry. If we wanted to enable [additional `revealjs` features](https://quarto.org/docs/presentations/revealjs/), then we would need to add each new feature similar to if we were just using the `revealjs` format, e.g.

```markdown
---
title: My Title
format:
  clean-revealjs:
    chalkboard: true
    incremental: true
author:
  - name: Neil Ernst
date: last-modified
---
```

If we just wanted the vanilla `revealjs` slides, we would have used `revealjs` in place of the `clean-revealjs` format:

```yaml
format:
  revealjs:
    chalkboard: true
    incremental: true
```

**Comment by grantmcdermott** [comment]
Thanks for jumping in @coatless. I've been traveling so didn't have a chance to respond yet. (As an side: I've found myself recommending your macrtools package to several people recently. Very cool.)

@neilernst Just to add one more point, the `default` argument is actually redundant here. I left it in because it makes it slightly more convenient when you are switching in non-default args like chalkboard. But for a plain vanilla doc, your YAML can just as well be:

```yaml
---
title: My Title
format: clean-revealjs
author:
  - name: Neil Ernst
date: last-modified
---
```

I might actually change the template YAML, so that this doesn't confuse others...
