### ISSUE TITLE
math display breaks when a tinytable is includedf´

### ISSUE THREAD

**Issue by m-g-h** [grantmcdermott/quarto-revealjs-clean#13]
The display of mathjax equations breaks when I include a tinytable. You can also see it on your slides: go to the Components - Blocks slide. The font of the equation is off, and if you try to render an integral it is completely broken.

**Comment by grantmcdermott** [comment]
I don't know what you mean by "include a tinytable". D you mean math rendering in the table itself, or the template as a whole? Please provide a MWE and/or screenshot in future.

Some comments:

- MathJax support is browser-dependent, so (again) it's hard to comment without a MWE or screenshot. For instance the demo slidedeck looks fine when rendered locally on my system. (Hosted rendering on GitHub etc. is a different issue, due to the combination of browser-dependency and the linked threads below.)

- There _are_ some upstream issues related to MathJax and (Quarto) Reveal.js that are not particularly limited to this template. ([Here](https://github.com/quarto-dev/quarto-cli/issues/9404) and [here](https://github.com/quarto-dev/quarto-cli/discussions/9009), for example.) In general, you have two options:

1) Either specify an updated MathJax CDN in your YAML:
 
   ```yaml
   format: clean-revealjs
   html-math-method:
     method: mathjax
     url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
   ```

2) Render via MathML instead of MathJax. Again, in your YAML:

   ```yaml
   format: clean-revealjs
   html-math-method:
     method: mathml
   ```

Final point: Again, because of variation across browser support (true for both the MathJax and MathML engines) your best bet is to use a common, standalone browser like Firefox or Chrome. Rendering from inside RStudio or VS Code is not a fair test.

Closing now, since these are upstream issues with workarounds per the above. But let me know if neither solves the problem for you.
