### ISSUE TITLE
Display of loose

### ISSUE THREAD

**Issue by harrysw1729** [grantmcdermott/quarto-revealjs-clean#15]
Currently, there is a line break between a nested list's marker and the item.

To illustrate the issue, install the extension to the project directory and consider the following `.qmd` document:

```qmd
## Slide

::: {.columns}

:::: {.column}

### Tight

- 1
  - 1.1
  - 1.2
- 2
  - 2.1
  - 2.2

::::

:::: {.column}

### Loose

- 1

  - 1.1

  - 1.2

- 2

  - 2.1

  - 2.2

::::

:::
```

For contrast, we create two Quarto profiles, one for the default revealjs, and the other for the clean theme.

```yml
# for the default theme
format:
  revealjs: default
output-file: foo.html
```

```yml
# for the clean theme
format:
  clean-revealjs: default
output-file: foo_clean.html
```

If we render the document with the two profiles, we get the following output for the default theme:
<img width="747" alt="image" src="https://github.com/user-attachments/assets/7758fac0-db6e-479c-b6bd-295c090a0d3d">

In contrast, the clean theme has the following display:
<img width="710" alt="image" src="https://github.com/user-attachments/assets/5396e26a-6705-4089-9c26-f925d6ee282c">

For the clean theme, in the loose list, there is a line break between item 1.1 and its marker; the line break does not exist for the tihgt list. In contrast, for the default theme, there is no line break between item 1.1 and its marker for tight or loose lists.

Thank you very much for your help.
