### ISSUE TITLE
adding logo

### ISSUE THREAD

**Issue by Dr-Eti** [grantmcdermott/quarto-revealjs-clean#17]
Hi thanks for this great template. However I've been experiencing an issue when trying to add a logo via the usual logo YAML  key e.g.,

```
---     
format:    
  clean-revealjs:      
    logo: logo.png      
    footer: "Footer text"         
---
```

Doing this seems to move the slide counter from the lower-right to the upper-right corner, causing it to overlap with the navigation menu button (which is located in the bottom left corner of the presentation when not using your template).
Is there a workaround besides setting both menu and slide-number to false? More generally, is there a way to accommodate one or more logos to the left and right side of the footer in each slide? Thank  you

**Comment by grantmcdermott** [comment]
Oof, sorry I never gave much thought to logos for this theme. I don't have time to dive into this rn but my guess is that we'll need to add some explicit scss logo adjustments [menu positions](https://github.com/grantmcdermott/quarto-revealjs-clean/blob/aded1c268758f0ea1e277661fa704b28db945eca/_extensions/clean/clean.scss#L180). Happy to consider a PR if you figure it out...

**Comment by grantmcdermott** [comment]
@Dr-Eti Logo support should be working correctly following #20. ("Correctly" here means that logos are automatically placed on the left and don't interfere with the other elements.)

Quick example:

```yaml
---
title: A title
subtitle: A subtitle
format:
  clean-revealjs:
    logo: quarto.png  
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
author:
  - name: Your Name
    orcid: 0000-0000-0000-0000
    email: alias@email.com
    affiliations: Your Institution
date: last-modified
---
```

![Image](https://github.com/user-attachments/assets/28cab807-18bb-4fe0-b8b6-388f6056d414)
