### ISSUE TITLE
`.bottom-left` class

### ISSUE THREAD

**Issue by kylebutts** [grantmcdermott/quarto-revealjs-clean#5]
It would be easy to put buttons in bottom-left with:

```css
// Put in bottom-left corner
.bottom-left {
  position: absolute;
  bottom: 10px;
  left:   10px;
}
```

The main problem is that each slide is wrapped in a `<section>` tag that has `position: relative` attached to it. So the absolute position is relative to that instead of the full screen. This works except for when text overflows in the vertical direction, making the button cover some of the text
