### ISSUE TITLE
Adding a logo to the bottom left corner

### ISSUE THREAD

**Issue by raheems** [grantmcdermott/quarto-revealjs-clean#6]
Wanted to add a logo to the bottom left of the slides. 

When using the following css file, it works but the page numbers move up to the top right corner. I want to avoid that. 

Could you please suggest how to do this?

```
title: "Title"
format:
  clean-revealjs:
    self-contained: true
    logo: logo.png
    css: logo.css
```

And here's the logo.css file

```
.reveal .slide-logo {
  display: block;
  position: fixed;
  top: unset !important;
  right: unset !important;
  top: 5px;
  left: 12px;
  height: 50px !important;
  width: 70x !important;
  max-width: unset !important;
  max-height: unset !important;
}
```
